---
- name: provision E-Heritage server
  hosts: all
  sudo: True

  roles:
    - ansible-elasticsearch

  tasks:
  # - name: Update apt-cache
  #   apt: update_cache=yes


  - name: install nginx
    apt: pkg=nginx state=present

  - name: ensure nginx is running
    service: name=nginx enabled=yes state=started

  - name: ensure elasticsearch is running
    service: name=elasticsearch enabled=yes state=started


### Install Elastic Search
  # - name: install apt_repository dependencies
  #   apt: pkg={{ item }} state=present
  #   with_items:
  #     - python-apt
  #     - python-pycurl

  # - name: add elastic search key
  #   apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

  # - name: add elastic search repo
  #   apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main' state=present

  # - name: install elasticsearch
  #   apt: pkg=elasticsearch state=present update_cache=yes

  # - name: ensure elasticsearch is running
  #   service: name=elasticsearch state=started

  vars_files:
  - vars/my-vars.yml